CC = gcc
CFLAGS = -Wall -Wextra -g

strace_0: strace_0.c
	$(CC) $(CFLAGS) -o strace_0 strace_0.c

strace_1: strace_1.c
	$(CC) -Wall -Wextra -Werror -pedantic -std=gnu99 strace_1.c -o strace_1

strace_2: strace_2.c
	$(CC) -Wall -Wextra -O2 -g -o strace_2 strace_2.c